#!/bin/bash

sm -f --start ASSETS_FRONTEND -r 3.11.0

sm -f --start MONGO DATASTREAM EMAIL HMRC_EMAIL_RENDERER MAILGUN_STUB DESKPRO_STUB HMRCDESKPRO

sm --start API_GATEWAY_STUB THIRD_PARTY_APPLICATION THIRD_PARTY_DEVELOPER API_SUBSCRIPTION_FIELDS API_DEFINITION THIRD_PARTY_DELEGATED_AUTHORITY

./run_local.sh
